export const products = [
  {
    id: '1',
    name: 'Produto 1',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 9.99,
    stock: 13,
  },
  {
    id: '2',
    name: 'Produto 2',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 14.99,
    stock: 27,
  },
  {
    id: '3',
    name: 'Produto 3',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 19.99,
    stock: 3,
  },
  {
    id: '4',
    name: 'Produto 4',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 24.99,
    stock: 50,
  },
  {
    id: '5',
    name: 'Produto 5',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 29.99,
    stock: 8,
  },
  {
    id: '6',
    name: 'Produto 6',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 34.99,
    stock: 45,
  },
  {
    id: '7',
    name: 'Produto 7',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 39.99,
    stock: 0,
  },
  {
    id: '8',
    name: 'Produto 8',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 44.99,
    stock: 16,
  },
  {
    id: '9',
    name: 'Produto 9',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 49.99,
    stock: 21,
  },
  {
    id: '10',
    name: 'Produto 10',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 54.99,
    stock: 5,
  },
  {
    id: '11',
    name: 'Produto 11',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 59.99,
    stock: 38,
  },
  {
    id: '12',
    name: 'Produto 12',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 64.99,
    stock: 47,
  },
  {
    id: '13',
    name: 'Produto 13',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 69.99,
    stock: 10,
  },
  {
    id: '14',
    name: 'Produto 14',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 74.99,
    stock: 29,
  },
  {
    id: '15',
    name: 'Produto 15',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 79.99,
    stock: 1,
  },
  {
    id: '16',
    name: 'Produto 16',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 84.99,
    stock: 33,
  },
  {
    id: '17',
    name: 'Produto 17',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 89.99,
    stock: 26,
  },
  {
    id: '18',
    name: 'Produto 18',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 94.99,
    stock: 44,
  },
  {
    id: '19',
    name: 'Produto 19',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 99.99,
    stock: 17,
  },
  {
    id: '20',
    name: 'Produto 20',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 104.99,
    stock: 12,
  },
  {
    id: '21',
    name: 'Produto 21',
    image: require('../assets/imgs/product1.png'),
    images: [
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
      require('../assets/imgs/product1.png'),
    ],
    price: 109.99,
    stock: 6,
  },
];
